[build]
 functions = "lambda"

 command = "echo ACCESS_TOKEN"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
 publish = "public/"
 command = "npm run prod"
 environment = { GATSBY_CONTENTFUL_SPACE_ID = "3z8evcxuelp4", GATSBY_CONTENTFUL_ACCESS_TOKEN = "kUw9-v7AqmHyaMuyvLYEv1qETxhLT5CLU_Cd6Jy8xKQ", GATSBY_URI = "https://jacketstore.netlify.app/.netlify/functions/gql_server", NODE_VERSION = "13.9.0", YARN_VERSION ="1.17.3"}


  